version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: 2023.08.1-node
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Build android
          command: |
            yarn run react-native link
            yarn run react-native run-android
